apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: production
  labels:
    app: analytics-service
spec:
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
  selector:
    app: analytics-service
  type: NodePort
